name: sarbon_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # di
  get_it: ^7.6.6
  # equatable
  equatable: ^2.0.5
  # async
  async: ^2.11.0
  # state manager
  flutter_bloc: ^8.1.3
  # hive
  hive: ^2.2.3
  # path
  path_provider: ^2.1.1
  # rest api
  dio: ^5.4.0
  dio_retry_plus: ^2.0.5
  # box
  gap: ^3.0.1
  # router
  go_router: ^13.0.1
  # svg
  flutter_svg: ^2.0.9
  # another flushbar
  another_flushbar: ^1.12.30
  # url launchers
  url_launcher: ^6.2.2
  # for map launch in phone map
  map_launcher: ^3.1.0
  # package info
  package_info_plus: ^6.0.0
  # cached image
  cached_network_image: ^3.3.1
  # image picker
  image_picker: ^1.0.7
  # native splash
  flutter_native_splash: ^2.4.4
  # firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8
  # local notification
  flutter_local_notifications: ^17.2.2
  # location
  location: ^5.0.0
  geolocator: ^10.1.1
  yandex_mapkit: ^3.4.0
  # interceptor
  chuck_interceptor: ^2.1.3
  # sms auto fill
  pinput: ^5.0.0
  # permission handler
  permission_handler: ^11.2.0
  dropdown_button2: ^2.3.9
  syncfusion_flutter_datepicker: ^24.1.45
  flutter_widget_from_html: ^0.15.3
  flutter_cache_manager: ^3.3.1
  hive_flutter: ^1.1.0
  geocoding: ^2.2.0
  device_info_plus: ^9.1.2
  battery_plus: ^6.0.1
  # image
  image_cropper: ^5.0.1
  # http parser
  http_parser: ^4.0.2
  share_plus: ^8.0.3
  dropdown_search: ^5.0.6
  # google sign in
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/locale/
    - assets/icons/
    - assets/images/
    - assets/gifs/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
# flutter_native_splash-production.yaml
flutter_native_splash:
  color: "#26BD49"
  color_dark: "#26BD49"

  android_12:
    icon_background_color: "#26BD49"
    icon_background_color_dark: "#26BD49"

  web: false