class SvgImage {
  SvgImage._();

  static const String addImages = 'assets/icons/add_image.svg';
  static const String successZoom = 'assets/icons/success_zoom.svg';
  static const String icRadioOn = 'assets/icons/ic_radio_on_24.svg';
  static const String icRadioOff = 'assets/icons/ic_radio_off_24.svg';
  static const String searchEmpty = 'assets/icons/search_empty.svg';
  static const String iconsIcFilter = 'assets/icons/ic_filter.svg';
  static const String locationMarker = 'assets/icons/location_marker.svg';
  static const String icHome = 'assets/icons/ic_home.svg';
  static const String inActiveNotification = 'assets/icons/in_active_notification.svg';
  static const String notificationChat = 'assets/icons/notification_chat.svg';
  static const String icArrowDropdown = 'assets/icons/ic_arrow_dropdown.svg';
  static const String calendar = 'assets/icons/calendar.svg';
  static const String deleteZoomRed = 'assets/icons/delete_zoom_red.svg';
  static const String icArrowRight = 'assets/icons/ic_arrow_right.svg';
  static const String icBellNotification = 'assets/icons/ic_bell_notification.svg';
  static const String routeActive = 'assets/icons/route_active.svg';
  static const String searchInActive = 'assets/icons/search_inactive.svg';
  static const String searchActive = 'assets/icons/search_active.svg';
  static const String marshrutIcon = 'assets/icons/marshrut_icon.svg';
  static const String ordersInActive = 'assets/icons/orders_inactive.svg';
  static const String ordersActive = 'assets/icons/orders_active.svg';
  static const String profileInActive = 'assets/icons/profile_inactive.svg';
  static const String profileActive = 'assets/icons/profile_active.svg';
  static const String icBack = 'assets/icons/ic_back.svg';
  static const String icLoading = 'assets/icons/ic_loading.svg';
  static const String icCarService = 'assets/icons/ic_car_service.svg';
  static const String icBoxDelivery = 'assets/icons/ic_box_delivery.svg';
  static const String icUser2 = 'assets/icons/ic_user_2.svg';
  static const String icTruck = 'assets/icons/ic_truck.svg';
  static const String icPackageSearch = 'assets/icons/ic_package_search.svg';
  static const String icHourglass = 'assets/icons/ic_hourglass.svg';
  static const String warningZoom = 'assets/icons/warning_zoom.svg';

  // static const String icSplashLogo = 'assets/icons/ic_splash_logo.svg';
  static const String icChevronRight = 'assets/icons/ic_chevron_right.svg';
  static const String icBackButton = 'assets/icons/ic_back_button.svg';
  static const String icMapMark = 'assets/icons/ic_map_mark.svg';
  static const String icBalance = 'assets/icons/ic_balance.svg';
  static const String logOutZoom = 'assets/icons/log_out_zoom.svg';
  static const String icCamera = 'assets/icons/ic_camera.svg';
  static const String icFilePlus = 'assets/icons/ic_file_plus.svg';
  static const String icFile = 'assets/icons/ic_file.svg';
  static const String icDownload = 'assets/icons/ic_download.svg';
  static const String icTrash = 'assets/icons/ic_trash.svg';
  static const String icFavourite = 'assets/icons/ic_favourite.svg';
  static const String icMyCars = 'assets/icons/ic_my_cars.svg';
  static const String icUsers = 'assets/icons/ic_users.svg';
  static const String icCalculator = 'assets/icons/ic_calculator.svg';
  static const String icNote = 'assets/icons/ic_note.svg';
  static const String icReport = 'assets/icons/ic_report.svg';
  static const String icChangeLanguage = 'assets/icons/ic_change_language.svg';
  static const String icLogOut = 'assets/icons/ic_log_out.svg';
  static const String icLocationOn = 'assets/icons/ic_location_on.svg';
  static const String icCalendarToday = 'assets/icons/ic_calendar_today.svg';
  static const String contactUs = 'assets/icons/contact_us.svg';

  /// new design
  static const String filterIcon = 'assets/icons/filter_icon.svg';
  static const String starIcon = 'assets/icons/star_icon.svg';
  static const String shareIcon = 'assets/icons/share_icon.svg';
  static const String likeIcon = 'assets/icons/like_icon.svg';
  static const String locationIcon = 'assets/icons/location_icon.svg';
  static const String truckIcon = 'assets/icons/truck_icon.svg';
  static const String truckGreenIcon = 'assets/icons/truck_green_icon.svg';
  static const String dumbellIcon = 'assets/icons/dumbell_icon.svg';
  static const String kubIcon = 'assets/icons/kub_icon.svg';
  static const String verificationIcon = 'assets/icons/verification_icon.svg';
  static const String warningOrder = 'assets/icons/warning_order.svg';
  static const String warningRed = 'assets/icons/warning_red.svg';
}
